namespace Randomizer
{
	/// <summary>
	/// An enum containing all the weapon indexes
	/// </summary>
	public enum WeaponIndexes
	{
		RustySword = 0,
		SilverSaber,
		DarkSword,
		HolyBlade,
		GalaxySword,
		BoneSword,
		IronEdge,
		TemplarsBlade,
		ObsidianEdge,
		LavaKatana,
		Claymore,
		SteelSmallsword,
		WoodenBlade,
		InsectHead,
		NeptunesGlaive,
		ForestSword,
		CarvingKnife,
		IronDirk,
		BurglarsShank,
		ShadowDagger,
		ElfBlade,
		CrystalDagger,
		WindSpire,
		GalaxyDagger,
		WoodClub,
		AlexsBat,
		LeadRod,
		WoodMallet,
		TheSlammer,
		GalaxyHammer,
		SamsOldGuitar,
		Femur,
		Slingshot,
		MasterSlingshot,
		GalaxySlingshot,
		ElliottsPencil,
		MarusWrench,
		HarveysMallet,
		PennysFryer,
		LeahsWhittler,
		AbbysPlanchette,
		SebsLostMace,
		HaleysIron,
		PiratesSword,
		Cutlass,
		WickedKris,
		Kudgel,
		Scythe,
		YetiTooth,
		Rapier,
		SteelFalchion,
		BrokenTrident,
		TemperedBroadsword,
		GoldenScythe = 53,
		DwarfSword = 54,
		DwarfHammer = 55,
		DwarfDagger = 56,
        DragontoothCutlass = 57,
		DragontoothClub = 58,
        DragontoothShiv = 59,
        OssifiedBlade = 60,
        IridiumNeedle = 61,
        InfinityBlade = 62,
        InfinityGavel = 63,
        InfinityDagger = 64,
		Meowmere = 65,
		IridiumScythe = 66
    }
}